<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
  </PropertyGroup>
  <PropertyGroup>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>x64</Platforms>
    <ForceDesignerDpiUnaware>true</ForceDesignerDpiUnaware>
    <Title>LEHuDMoDLauncher</Title>
    <Description>LEHuDMoDLauncher Last Epoch HUD Mod</Description>
    <Copyright>Ash</Copyright>
    <AssemblyVersion>1.0.1</AssemblyVersion>
    <FileVersion>1.0.1</FileVersion>
    <Configurations>Debug;DebugNew;Release</Configurations>
    <ApplicationIcon>gooey-daemon_multi2.ico</ApplicationIcon>
    <BaseOutputPath>bin\Release</BaseOutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <DebugType>none</DebugType>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='DebugNew|x64'">
    <DebugType>none</DebugType>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <DebugType>none</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AssetsTools.NET" Version="3.0.4">
      <TreatAsUsed>true</TreatAsUsed>
    </PackageReference>
    <PackageReference Include="MaterialSkin.2" Version="2.3.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4">
      <TreatAsUsed>true</TreatAsUsed>
    </PackageReference>
    <PackageReference Include="SharpCompress" Version="0.47.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DownloadLib\DownloadLib.csproj" />
    <ProjectReference Include="..\LogUtils\LogUtils.csproj" />
    <ProjectReference Include="..\SettingsManager\SettingsManager.csproj" />
  </ItemGroup>


</Project>
